baseurl: "http://adamisrael.com/"
languageCode: "en-us"
title: "Adam Israel"
theme: "material-design"
copyright: "© 2016 Adam Israel"

permalinks:
  post: /:year/:month/:day/:title/

params:
  description: "An economy of words"
  Subtitle: ""
  AuthorName: "AdamIsrael"
  twitter: "AdamIsrael"
  github: "AdamIsrael"
  facebook: "adam.israel"
  email: "adam@adamisrael.com"
  gplus: "AdamIsrael1975"

  headerCover: "images/header.jpg"
  footerCover: "images/footer.jpg"
  googleAnalytics: "UA-12202287-1"
  googleAnalyticsUserID: "UA-12202287-1"

  disqusShortname: "adamisrael"
  # description = "Your Site Description" # optional
  # twitter = "Your Twitter Name" # optional
  # github = "Your Github Name" # optional
  # facebook = "Your facebook Name" # optional
  # gplus = "Your Google+ profile name" # optional
  # linkedin = "Your LinkedIn Name" # optional
  # headerCover = "images/headerCover.png" # optional
  # footerCover = "images/footerCover.png" # optional
  # googleAnalyticsUserID = "Your Analytics User Id" # optional
  #
  ListOfFoo:
    - "foo1"
    - "foo2"
  SidebarRecentLimit: 5
